// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `Printer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public interface Printer extends Ice.Object,
                                 _PrinterOperations, _PrinterOperationsNC
{
    public static final String ice_staticId = "::Demo::Printer";

    public static final long serialVersionUID = 5653233674703040184L;
}
